#!/usr/bin/env node

// this script migrate tags and rating from old videodb to new dbjson

var _ = require('lodash');
var execSync = require("exec-sync");
var fs = require('fs');

var opts = require("nomnom")
  .script("migrate-dbjson")
  .option('input', {
      position: 0,
      help: "videodb to parse",
      required: true
  })
  .option('output', {
      position: 1,
      help: "dbjson to migrate to",
      required: true
  })
  .help("Author: ".bold +
    "leesei@gmail.com".underline + "       "+
    "Licence: ".bold + "MIT\n")
  .parse();

function loadJson(filepath) {
  return JSON.parse(fs.readFileSync(filepath, 'utf8'));
}

// parse { extractor, id } out of key from old dbjson
function getVideoSource(key) {
  var re = /\('(.+)',\s*'(.+)'\)/;
  var match = key.match(re);
  // console.log(match[1], match[2]);
  return (match)? {
    extractor: match[1],
    video_id: match[2]
  } : null;
}

// console.log(opts);

var failedEntries = {};
var videodb =  loadJson(opts.output);
if (!_.isArray(videodb)) {
  console.error('invalid out file:', opts.output);
  return;
}
// console.log(videodb);

_.forOwn(loadJson(opts.input), function(val, key) {
  // console.log(key);

  var source = getVideoSource(key);
  if (!source) {
    console.error('unknown source', key);
    failedEntries[key] = val;
    return;
  }
  var entry = _.find(videodb, function(e) {
    return (e.extractor == source.extractor &&
            e.video_id == source.video_id);
  });

  if (!entry) {
    console.error('entry not found', key);
    failedEntries[key] = val;
    return;
  }

  entry.tags = val.tags;
  entry.rating = val.rating;
});

console.info('migrated to ' + opts.output);
fs.writeFileSync(opts.output, JSON.stringify(videodb, null, 2));

var failOutfile = '4-failedEntries.json';
if (Object.keys(failedEntries).length !== 0) {
  console.error('failed on some entries, see ' + failOutfile);
  fs.writeFileSync(failOutfile, JSON.stringify(failedEntries, null, 2));
}

